# Generated by Django 3.0.2 on 2020-02-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItemsModel',
            fields=[
                ('ino', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('cno', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=10)),
                ('contactno', models.IntegerField()),
                ('foodid', models.ManyToManyField(to='app.FoodItemsModel')),
            ],
        ),
    ]
